wayland_titlebar_color system
linux_display_server auto
wayland_enable_ime yes
repaint_delay 10
input_delay 3
sync_to_monitor yes
shell .
editor .
close_on_child_death no

# remote_control_password
allow_remote_control no
listen_on none
# env
# filter_notification
# watcher
# exe_search_path
update_check_interval 24
startup_session none
clipboard_control write-clipboard write-primary read-clipboard-ask read-primary-ask
clipboard_max_size 512
# file_transfer_confirmation_bypass
allow_hyperlinks yes
shell_integration enabled
allow_cloning ask

# clone_source_strategies venv,conda,env_var,path
# - venv (Source the file $VIRTUAL_ENV/bin/activate. This is used by the Python stdlib venv module and allows cloning venvs automatically.)
# - conda (Run conda activate $CONDA_DEFAULT_ENV. This supports the virtual environments created by conda.)
# - env_var (Execute the contents of the environment variable KITTY_CLONE_SOURCE_CODE with eval.)
# - path (Source the file pointed to by the environment variable KITTY_CLONE_SOURCE_PATH.)

notify_on_cmd_finish never
# - never (Never send a notification)
# - unfocused (Only send a notification when the window does not have keyboard focus)
# - invisible (Only send a notification when the window both is unfocused and not visible)
# - always (Always send a notification, regardless of window state)

# term xterm-kitty
# terminfo_type path
# forward_stdio no
# menu_map
