##### FONT SETTINGS #####
font_family      monospace
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 11.0
force_ltr no
# symbol_map
# narrow_symbols
# disable_ligatures never
# font_features
# modify_font
box_drawing_scale 0.001, 1, 1.5, 2
undercurl_style thin-sparse
underline_exclusion 1
text_composition_strategy platform
text_fg_override_threshold 0


#### COLOUR SCHEME ####
background #141216
foreground #d8cab8
background_opacity 0.8 
background_blur 0
# transparent_background_colors
dynamic_background_opacity no
background_image none
background_image_layout tiled
background_image_linear no
background_tint 0.0
background_tint_gaps 1.0
dim_opacity 0.4
selection_background #d8cab8
selection_foreground #141216

color0 #2b2135
color8 #92fcfa
# black
color1 #fc4649
color9 #fc4649
# red
color2 #c4e881
color10 #c4e881
# green
color3 #AC82E9
color11 #AC82E9
# yellow
color4 #7b91fc
color12 #7b91fc
# blue
color5 #f3fc7b
color13 #f3fc7b
# magenta
color6 #8F56E1
color14 #8F56E1
# cyan
color7 #fc92fc
color15 #d8cab8

mark1_foreground black
mark1_background #98d3cb
mark2_foreground black
mark2_background #f2dcd3
mark3_foreground black
mark3_background #f274bc

#### CURSOR CONFIG ####
shell_integration no-cursor
cursor_shape beam
cursor #AC82E9
cursor_text_color #111111
cursor_shape block
cursor_shape_unfocused hollow
cursor_beam_thickness 1.5
cursor_underline_thickness 2.0
cursor_blink_interval -1
cursor_stop_blinking_after 15.0
cursor_trail 0
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
cursor_trail_color none

#### TERMINAL BELL ####
enable_audio_bell yes
visual_bell_duration 0.0
visual_bell_color none
window_alert_on_bell yes
bell_on_tab "🔔 "
command_on_bell none
macos_dock_badge_on_bell yes
bell_path none
linux_bell_theme __custom
