" Basic display / UI options
set number 
set norelativenumber 
"set cursorline
set nowrap
set scrolloff=50
set sidescrolloff=10

" Tab / indent settings
set tabstop=2
set shiftwidth=4
set softtabstop=2
set expandtab
set smartindent
set autoindent

" Search / match options
set ignorecase
set smartcase
set hlsearch
set incsearch

set colorcolumn=0
set showmatch

" Command line / popup menu options
set cmdheight=1
set showmode
set pumheight=10

" Update & timeout settings
set updatetime=300    " faster completion
set timeoutlen=500    " timeout duration
set ttimeoutlen=0     " key code timeout

" Error bells & backspace behavior
set noerrorbells
set backspace=indent,eol,start


" files (backup, swap, undo)
set nobackup
set nowritebackup
set noswapfile
set undofile

" change default vim-related file locations
let g:undodir = "~/.config/vim/undo"
set undodir=%g:undodir
set viminfo+=n~/.config/vim/viminfo

" Keyword / path options
set iskeyword+=-
set path+=**

" Selection mode
set selection=inclusive

" Mouse & clipboard
set mouse=a
set clipboard=unnamedplus

" Custom key mapping
let mapleader = " "          " use Space as the <Leader>
nnoremap <silent> <leader>cd :Ex<CR>
